# Generated by Django 6.0 on 2026-01-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="user_to_follow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="core.post",
            ),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(fields=["user"], name="core_follow_user_id_2a39fb_idx"),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(
                fields=["user_to_follow"], name="core_follow_user_to_0a4169_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("user", "user_to_follow")},
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["author"], name="core_reacti_author__69a974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(fields=["post"], name="core_reacti_post_id_e87da5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("author", "post")},
        ),
    ]
